# 테이블 생성
CREATE TABLE AUTH_NAMES
(
  AUTH_NAME VARCHAR(200) NOT NULL COMMENT '접근권한명',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '접근권한명';

CREATE TABLE AUTHS
(
  UNIQUE_ID_USERS      VARCHAR(200) NOT NULL COMMENT '대표값',
  UNIQUE_ID_AUTH_NAMES VARCHAR(200) NOT NULL COMMENT '접근권한 대표값'
) COMMENT '권한들';

CREATE TABLE USERS
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '대표값',
  NAME      VARCHAR(200) NOT NULL COMMENT '이름',
  EMAIL     VARCHAR(200) NOT NULL COMMENT '이메일',
  JOB       VARCHAR(200) NULL     COMMENT '직책',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '사용자들';

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_USERS_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_USERS)
    REFERENCES USERS (UNIQUE_ID);

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_AUTH_NAMES_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_AUTH_NAMES)
    REFERENCES AUTH_NAMES (UNIQUE_ID);

#데이터 입력
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U1','Paul','paul01@gmail.com','IT Billing')
;
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U2','Allen','texas@imfblog.org','Engineering')
;
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U3','Teddy','norway@iotm.com','IT Billing')
;
INSERT INTO users (UNIQUE_ID,NAME,EMAIL,JOB)
VALUES ('U4','Paul','paul_p@naver.com','Developer')
;

INSERT INTO auth_names (AUTH_NAME,UNIQUE_ID)
VALUES ('GUEST','B1')
;
INSERT INTO auth_names (AUTH_NAME,UNIQUE_ID)
VALUES ('ADMIN','B2')
;
INSERT INTO auth_names (AUTH_NAME,UNIQUE_ID)
VALUES ('MANAGER','B3')
;

INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U1','B1')
;
INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U1','B2')
;

INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U2','B1')
;
INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U2','B2')
;
INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U2','B3')
;
INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U3','B1')
;
INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U4','B2')
;
INSERT INTO auths (UNIQUE_ID_USERS,UNIQUE_ID_AUTH_NAMES)
VALUES ('U4','B1')
;

#삭제
# DELETE FROM table_name WHERE condition;
DELETE FROM auths 
WHERE UNIQUE_ID_USERS = 'U2';
DELETE FROM auths 
WHERE UNIQUE_ID_USERS = 'U4';

DELETE FROM users 
WHERE UNIQUE_ID = 'U2';
DELETE FROM users 
WHERE UNIQUE_ID = 'U4';

SELECT *
FROM users;

SELECT *
FROM auth_names;

SELECT *
FROM auths;
